        <footer>
                <div class="container-fluid1">
                    <div class="copyright">

                                <div class="row text-center">
                                    <p align="center" class="copyright">©2003-2018 Inmar Inc.</p>
                         </div>

                    </div>
                </div>
        </footer>

<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    </body>
</html>
