<?php include VIEW. 'header.phtml'; ?>
<div class="container top">
	<div class="row">
		<h2 class="signup text-center">Login</h2>
		<hr class="divider">

    	<div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
            <form id="basicBootstrapForm" class="form-horizontal" method="POST" action="">
			    <div class="form-group">
			        <label class="col-xs-3 control-label">Email address</label>
			        <div class="col-xs-5">
			            <input type="text" class="form-control" name="uname" placeholder="sample@inmar.com" />
			        </div>
			    </div>

			    <div class="form-group">
			        <label class="col-xs-3 control-label">Password</label>
			        <div class="col-xs-5">
			            <input type="password" class="form-control" name="pword" placeholder="password" />
			        </div>
			    </div>

			    <div class="form-group">
			        <div class="col-xs-9 col-xs-offset-3 center">
			            <button type="submit" class="btn btn-primary" name="btnSubmit" value="login">Login</button>
			        </div>
			    </div>
                </form>
			<div class="text-center">
    
		        <p>Don't have an account?</p>
		        <p><a class="register-account toggle-register-login" href="signup">Create an account</a></p>
		    </div>

		</div>
	</div>
</div>
<?php include VIEW . 'footer.phtml';