<?php include VIEW . 'header.phtml'; ?>
<script>
    // method to validate the values entered by the user
    function validateSignupForm() {
        var pattern = new RegExp("[a-z][^a-z0-9]*@inmar\\.com", "ig"); // regular expression
        
        var email = document.forms["signup"]["email"].value; // entered email
        if (!pattern.test(email)) { // check whether the email is matching the pattern or not
            alert("E-mail is invalid\n Ex: anything@inmar.com"); // if not, alert the user
            return false;
        }
        
        pattern = new RegExp("^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$", "ig"); // regular expression
        var mobile = document.forms["signup"]["mobile"].value; // entered mobile number
        if (!pattern.test(mobile)) { // check whether the mobile is matching the pattern or not
            alert("Mobile number is invalid\n Ex: enter exactly 10 digits"); // if not, alert the user
            return false;
        }
    }
</script>
<div class="container top">
	<div class="row">
		<h2 class="signup text-center">Create an account</h2>
		<hr class="divider">

    	<div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
            <form name="signup" id="basicBootstrapForm" class="form-horizontal" method="post" action="" onsubmit="return validateForm()">
			    <div class="form-group">
			        <label class="col-xs-3 control-label">Full Name</label>
			        <div class="col-xs-4">
			            <input type="text" class="form-control" name="firstName" placeholder="First name" />
			        </div>
			        <div class="col-xs-4">
			            <input type="text" class="form-control" name="surName" placeholder="Last name" />
			        </div>
			    </div>

			    <div class="form-group">
			        <label class="col-xs-3 control-label">Aadhar</label>
			        <div class="col-xs-8">
			            <input type="number" class="form-control" name="aadhar" placeholder="aadhar number" />
			        </div>
			    </div>

			    <div class="form-group">
			        <label class="col-xs-3 control-label">Email address</label>
			        <div class="col-xs-8">
			            <input type="email" class="form-control" name="email" placeholder="sample@inmar.com" />
			        </div>
			    </div>
                            <div class="form-group">
			        <label class="col-xs-3 control-label">Mobile no.</label>
			        <div class="col-xs-8">
			            <input type="number" class="form-control" name="mobile" placeholder="mobile" />
			        </div>
			    </div>

			    <div class="form-group">
			        <label class="col-xs-3 control-label">Password</label>
			        <div class="col-xs-8">
			            <input type="password" class="form-control" name="password" placeholder="password" />
			        </div>
			    </div>

			    <div class="form-group">
			        <label class="col-xs-3 control-label">Gender</label>
                                <div class="col-xs-12 col-sm-3 col-md-3 radio">
                                            <label>
                                                <input type="radio" name="gender" value="Male" /> Male
                                            </label>
                                </div>
                                <div class="col-xs-12 col-sm-3 col-md-3 radio">
                                            <label>
                                                <input type="radio" name="gender" value="Female" /> Female
                                            </label>
                                </div>
                                <div class="col-xs-12 col-sm-3 col-md-3 radio">
                                            <label>
                                                <input type="radio" name="gender" value="Other" /> Other
                                            </label>
                                </div>
			    </div>

			    <div class="form-group">
			        <label class="col-xs-3 control-label">Address-1</label>
			        <div class="col-xs-4">
			            <input type="text" class="form-control" name="line_1" placeholder="line_1" />
			        </div>
                                <div class="col-xs-4">
			            <input type="text" class="form-control" name="city" placeholder="city" />
			        </div>
			    </div>
                    
                    
                            <div class="form-group">
			        <label class="col-xs-3 control-label">Address-2</label>
                                <div class="col-xs-4">
			            <input type="text" class="form-control" name="state" placeholder="state" />
			        </div>
			        <div class="col-xs-4">
			            <input type="text" class="form-control" name="country" placeholder="country" />
			        </div>
			    </div>
                            
                            <div class="form-group">
                                <label class="col-xs-3 control-label">Zipcode</label>
                                <div class="col-xs-8">
                                    <input type="number" class="form-control" name="zipcode" placeholder="zipcode" />
			        </div>
                            </div>
                    

			    <div class="form-group">
			        <div class="col-xs-12 col-xs-offset-3">
			            <div class="checkbox">
			                <label>
			                    <input type="checkbox" name="agree" value="agree" /> Agree with the terms and conditions
			                </label>
			            </div>
			        </div>
			    </div>

			    <div class="form-group">
			        <div class="col-xs-9 col-xs-offset-3">
			            <button type="submit" class="btn btn-primary" name="btnSignup" value="Sign up">Submit</button>
			        </div>
			    </div>
			</form>
			<div class="text-center">
    
                            <p> Already have an account?</p>
                            <p><a class="register-account toggle-register-login" href="login">Login here</a></p>
                        </div>
		</div>
	</div>
</div>
<?php include VIEW. 'footer.phtml';
	