<?php include VIEW . 'header.phtml'; ?>
<div class="container top">
	<div class="row">
		<h2 class="signup text-center">Create an account</h2>
		<hr class="divider">

    	<div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
            <form id="basicBootstrapForm" class="form-horizontal" method="post" action="">
			    <div class="form-group">
			        <label class="col-xs-3 control-label">Full Name</label>
			        <div class="col-xs-4">
			            <input type="text" class="form-control" name="firstName" placeholder="First name" />
			        </div>
			        <div class="col-xs-4">
			            <input type="text" class="form-control" name="surName" placeholder="Last name" />
			        </div>
			    </div>

			    <div class="form-group">
			        <label class="col-xs-3 control-label">Aadhar</label>
			        <div class="col-xs-5">
			            <input type="number" class="form-control" name="aadhar" placeholder="aadhar number" />
			        </div>
			    </div>

			    <div class="form-group">
			        <label class="col-xs-3 control-label">Email address</label>
			        <div class="col-xs-5">
			            <input type="email" class="form-control" name="email" placeholder="sample@inmar.com" />
			        </div>
			    </div>
                            <div class="form-group">
			        <label class="col-xs-3 control-label">Mobile no.</label>
			        <div class="col-xs-5">
			            <input type="number" class="form-control" name="mobile" placeholder="mobile" />
			        </div>
			    </div>

			    <div class="form-group">
			        <label class="col-xs-3 control-label">Password</label>
			        <div class="col-xs-5">
			            <input type="password" class="form-control" name="password" placeholder="password" />
			        </div>
			    </div>

			    <div class="form-group">
			        <label class="col-xs-3 control-label">Gender</label>
                                <div class="col-xs-12 col-md-3 radio">
                                            <label>
                                                <input type="radio" name="gender" value="Male" /> Male
                                            </label>
                                </div>
                                <div class="col-xs-12 col-md-3 radio">
                                            <label>
                                                <input type="radio" name="gender" value="Female" /> Female
                                            </label>
                                </div>
                                <div class="col-xs-12 col-md-3 radio">
                                            <label>
                                                <input type="radio" name="gender" value="Other" /> Other
                                            </label>
                                </div>
			    </div>

			    <div class="form-group">
			        <label class="col-xs-3 control-label">Address</label>
			        <div class="col-xs-3">
			            <input type="text" class="form-control" name="line_1" placeholder="line_1" />
			        </div>
                                <div class="col-xs-3">
			            <input type="text" class="form-control" name="city" placeholder="city" />
			        </div>
                                <div class="col-xs-3">
			            <input type="text" class="form-control" name="state" placeholder="state" />
			        </div>
                                
			    </div>
                    
                    
                            <div class="form-group">
			        <label class="col-xs-3 control-label">Address</label>
			        <div class="col-xs-3">
			            <input type="text" class="form-control" name="country" placeholder="country" />
			        </div>
                                <div class="col-xs-3">
                                    <input type="number" class="form-control" name="zipcode" placeholder="zipcode" />
			        </div>
                                
			    </div>
                    

			    <div class="form-group">
			        <div class="col-xs-6 col-xs-offset-3">
			            <div class="checkbox">
			                <label>
			                    <input type="checkbox" name="agree" value="agree" /> Agree with the terms and conditions
			                </label>
			            </div>
			        </div>
			    </div>

			    <div class="form-group">
			        <div class="col-xs-9 col-xs-offset-3">
			            <button type="submit" class="btn btn-primary" name="btnSignup" value="Sign up">Submit</button>
			        </div>
			    </div>
			</form>
			<div class="text-center">
    
		        <p> Already have an chat account?</p>
		        <p><a class="register-account toggle-register-login" href="login">Login here</a></p>
		    </div>
		</div>
	</div>
</div>
<?php include VIEW. 'footer.phtml';
	