<?php include VIEW . 'header.phtml'; ?>
<?php include VIEW . 'user'.DIRECTORY_SEPARATOR.'menu.phtml'?>

<div class="container top">
	<div class="row">
		<h2 class="signup text-center">Delete A Contact</h2>
		<hr class="divider">

    	<div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
            <form id="basicBootstrapForm" class="form-horizontal" method="POST" action="">
		<div class="form-group">
		    <label class="col-xs-3 control-label">Enter Contact Id</label>
		    <div class="col-xs-4">
		        <input type="text" class="form-control" name="contact_id" placeholder="Enter contact id" />
		    </div>
		</div>

		<div class="form-group">
		    <div class="col-xs-9 col-xs-offset-3">
		        <button type="submit" class="btn btn-primary" name="btnDelete" value="Create">Delete</button>
		    </div>
                </div>
            </form>
        </div>
	</div>
</div>
<?php include VIEW. 'footer.phtml';
	

