<div class="col-sm-2 col-lg-2">
    <div class="sidebar-nav">
        <div class="nav-canvas">
            <div class="nav-sm nav nav-stacked"></div>
            <ul class="nav nav-pills nav-stacked main-menu">
                
                <li class="accordion">
                    <a class="ajax-link" href="/user/create_contact">
                        <i class="glyphicon glyphicon-edit"></i>
                        <span>Create Contact</span>
                    </a>
                </li>
                
                <li class="accordion">
                    <a class="ajax-link" href="/user/create_group">
                        <i class="glyphicon glyphicon-edit"></i>
                        <span>Create Group</span>
                    </a>
                </li>
                
                <li class="accordion">
                    <a class="ajax-link" href="/user/view_contacts">
                        <i class="glyphicon glyphicon-edit"></i>
                        <span>View Contacts</span>
                    </a>
                </li>
                
                <li class="accordion">
                    <a class="ajax-link" href="/user/view_groups">
                        <i class="glyphicon glyphicon-edit"></i>
                        <span>View Groups</span>
                    </a>
                </li>
                
                <li class="accordion">
                    <a class="ajax-link" href="/user/search">
                        <i class="glyphicon glyphicon-edit"></i>
                        <span>Search Contact</span>
                    </a>
                </li>
                
                <li class="accordion">
                    <a class="ajax-link" href="/user/delete_group">
                        <i class="glyphicon glyphicon-edit"></i>
                        <span>Delete Group</span>
                    </a>
                </li>
                
                <li class="accordion">
                    <a class="ajax-link" href="/user/delete_contact">
                        <i class="glyphicon glyphicon-edit"></i>
                        <span>Delete Contact</span>
                    </a>
                </li>
                
                <li class="accordion">
                    <a class="ajax-link" href="/account/logout">
                        <i class="glyphicon glyphicon-edit"></i>
                        <span>Logout</span>
                    </a>
                </li>
                
            </ul>
        </div>
    </div>
</div>
